//
//  Localization.swift
//  SEDProfessor
//
//  Created by Victor Bozelli Alvarez on 13/11/18.
//  Copyright © 2018 PRODESP. All rights reserved.
//

import Foundation

final class Localization {
    static let alunos = "br.gov.sp.educacao.sedprofessor.alunos"
    static let alunoDetalhe = "br.gov.sp.educacao.sedprofessor.alunoDetalhe"
    static let anterior = "br.gov.sp.educacao.sedprofessor.anterior"
    static let atencao = "br.gov.sp.educacao.sedprofessor.atencao"
    static let avaliacaoLancamento = "br.gov.sp.educacao.sedprofessor.avaliacaoLancamento"
    static let ativo = "br.gov.sp.educacao.sedprofessor.ativo"
    static let atualizadaComSucesso = "br.gov.sp.educacao.sedprofessor.atualizadaComSucesso"
    static let autenticandoUsuario = "br.gov.sp.educacao.sedprofessor.autenticandoUsuario"
    static let avaliacao = "br.gov.sp.educacao.sedprofessor.avaliacao"
    static let avaliarAplicativo = "br.gov.sp.educacao.sedprofessor.avaliarAplicativo"
    static let avaliarAplicativoAppStore = "br.gov.sp.educacao.sedprofessor.avaliarAplicativoAppStore"
    static let avisoRedesMoveis = "br.gov.sp.educacao.sedprofessor.avisoRedesMoveis"
    static let avisoSemInternet = "br.gov.sp.educacao.sedprofessor.avisoSemInternet"
    static let baixandoDados = "br.gov.sp.educacao.sedprofessor.baixandoDados"
    static let bimestreSelecionado = "br.gov.sp.educacao.sedprofessor.bimestreSelecionado"
    static let cadastradaComSucesso = "br.gov.sp.educacao.sedprofessor.cadastradaComSucesso"
    static let cancelar = "br.gov.sp.educacao.sedprofessor.cancelar"
    static let carregando = "br.gov.sp.educacao.sedprofessor.carregando"
    static let compareceu = "br.gov.sp.educacao.sedprofessor.compareceu"
    static let compartilhar = "br.gov.sp.educacao.sedprofessor.compartilhar"
    static let confirmar = "br.gov.sp.educacao.sedprofessor.confirmar"
    static let confirmado = "br.gov.sp.educacao.sedprofessor.confirmado"
    static let confirmarLancamentoFechamento = "br.gov.sp.educacao.sedprofessor.confirmarLancamentoFechamento"
    static let conflitoFrequencia = "br.gov.sp.educacao.sedprofessor.conflitoFrequencia"
    static let conflitoFrequenciaOffline = "br.gov.sp.educacao.sedprofessor.conflitoFrequenciaOffline"
    static let conteudos = "br.gov.sp.educacao.sedprofessor.conteudos"
    static let consulta = "br.gov.sp.educacao.sedprofessor.consulta"
    static let cpf = "br.gov.sp.educacao.sedprofessor.cpf"
    static let dadosIncompletosServidor = "br.gov.sp.educacao.sedprofessor.dadosIncompletosServidor"
    static let dadosNaoForamBaixados = "br.gov.sp.educacao.sedprofessor.dadosNaoForamBaixados"
    static let datasFuturas = "br.gov.sp.educacao.sedprofessor.datasFuturas"
    static let desejaSair = "br.gov.sp.educacao.sedprofessor.desejaSair"
    static let detalheConflito = "br.gov.sp.educacao.sedprofessor.detalheConflito"
    static let diaLetivoNaoEncontrado = "br.gov.sp.educacao.sedprofessor.diaLetivoNaoEncontrado"
    static let erroCadastrarAtividade = "br.gov.sp.educacao.sedprofessor.erroCadastrarAtividade"
    static let erroDesconhecido = "br.gov.sp.educacao.sedprofessor.erroDesconhecido"
    static let erroFechamentoTurma = "br.gov.sp.educacao.sedprofessor.erroFechamentoTurma"
    static let excluindoFrequencia = "br.gov.sp.educacao.sedprofessor.excluindoFrequencia"
    static let excluindoFrequenciaPorFavorAguarde = "br.gov.sp.educacao.sedprofessor.excluindoFrequenciaPorFavorAguarde"
    static let existemDadosNaoSincronizados = "br.gov.sp.educacao.sedprofessor.existemDadosNaoSincronizados"
    static let faltou = "br.gov.sp.educacao.sedprofessor.faltou"
    static let fechamento = "br.gov.sp.educacao.sedprofessor.fechamento"
    static let fechamentoLancamento = "br.gov.sp.educacao.sedprofessor.fechamentoLancamento"
    static let finalizar = "br.gov.sp.educacao.sedprofessor.finalizar"
    static let finalizado = "br.gov.sp.educacao.sedprofessor.finalizado"
    static let frequencia = "br.gov.sp.educacao.sedprofessor.frequencia"
    static let frequenciaIncompleta = "br.gov.sp.educacao.sedprofessor.frequenciaIncompleta"
    static let frequenciaLancamento = "br.gov.sp.educacao.sedprofessor.frequenciaLancamento"
    static let frequenciaPeriodoNaoLetivo = "br.gov.sp.educacao.sedprofessor.frequenciaPeriodoNaoLetivo"
    static let habilidades = "br.gov.sp.educacao.sedprofessor.habilidades"
    static let inativo = "br.gov.sp.educacao.sedprofessor.inativo"
    static let inserirUsuarioSenha = "br.gov.sp.educacao.sedprofessor.inserirUsuarioSenha"
    static let insiraONomeDaAtividade = "br.gov.sp.educacao.sedprofessor.insiraONomeDaAtividade"
    static let lancamento = "br.gov.sp.educacao.sedprofessor.lancamento"
    static let limiteAulasPorSemanaDia = "br.gov.sp.educacao.sedprofessor.limiteAulasPorSemanaDia"
    static let limiteAulasPorSemanaHorario = "br.gov.sp.educacao.sedprofessor.limiteAulasPorSemanaHorario"
    static let listar = "br.gov.sp.educacao.sedprofessor.listar"
    static let medias = "br.gov.sp.educacao.sedprofessor.medias"
    static let mediasNaoArredondadadas = "br.gov.sp.educacao.sedprofessor.mediasNaoArredondadadas"
    static let nao = "br.gov.sp.educacao.sedprofessor.nao"
    static let naoAplicavel = "br.gov.sp.educacao.sedprofessor.naoAplicavel"
    static let naoFoiPossivelAcessarDados = "br.gov.sp.educacao.sedprofessor.naoFoiPossivelAcessarDados"
    static let nenhumaAulaEncontradaParaTurma = "br.gov.sp.educacao.sedprofessor.nenhumaAulaEncontradaParaTurma"
    static let nenhumaInformacaoParaSincronizar = "br.gov.sp.educacao.sedprofessor.nenhumaInformacaoParaSincronizar"
    static let nota = "br.gov.sp.educacao.sedprofessor.nota"
    static let notasAvaliacoesFuturas = "br.gov.sp.educacao.sedprofessor.notasAvaliacoesFuturas"
    static let numeroDeTurmas = "br.gov.sp.educacao.sedprofessor.numeroDeTurmas"
    static let ok = "br.gov.sp.educacao.sedprofessor.ok"
    static let paraATurma = "br.gov.sp.educacao.sedprofessor.paraATurma"
    static let permissaoAvaliacao = "br.gov.sp.educacao.sedprofessor.permissaoAvaliacao"
    static let permissaoFrequencia = "br.gov.sp.educacao.sedprofessor.permissaoFrequencia"
    static let preencherAulasPlanejadas = "br.gov.sp.educacao.sedprofessor.preencherAulasPlanejadas"
    static let preencherAulasRealizadas = "br.gov.sp.educacao.sedprofessor.preencherAulasRealizadas"
    static let preencherCampos = "br.gov.sp.educacao.sedprofessor.preencherCampos"
    static let preencherJustificativa = "br.gov.sp.educacao.sedprofessor.preencherJustificativa"
    static let professor = "br.gov.sp.educacao.sedprofessor.professor"
    static let proximo = "br.gov.sp.educacao.sedprofessor.proximo"
    static let realizadoComSucesso = "br.gov.sp.educacao.sedprofessor.realizadoComSucesso"
    static let registroDeAulas = "br.gov.sp.educacao.sedprofessor.registroDeAulas"
    static let registroSalvo = "br.gov.sp.educacao.sedprofessor.registroSalvo"
    static let registroPeriodoNaoLetivo = "br.gov.sp.educacao.sedprofessor.registroPeriodoNaoLetivo"
    static let rg = "br.gov.sp.educacao.sedprofessor.rg"
    static let replicarLancamentoParaOutraAula = "br.gov.sp.educacao.sedprofessor.replicarLancamentoParaOutraAula"
    static let sair = "br.gov.sp.educacao.sedprofessor.sair"
    static let sim = "br.gov.sp.educacao.sedprofessor.sim"
    static let sobre = "br.gov.sp.educacao.sedprofessor.sobre"
    static let sincronizar = "br.gov.sp.educacao.sedprofessor.sincronizar"
    static let sincronizando = "br.gov.sp.educacao.sedprofessor.sincronizando"
    static let status = "br.gov.sp.educacao.sedprofessor.status"
    static let sucessoFrequencia = "br.gov.sp.educacao.sedprofessor.sucessoFrequencia"
    static let sucessoNotas = "br.gov.sp.educacao.sedprofessor.sucessoNotas"
    static let sucessoRegistro = "br.gov.sp.educacao.sedprofessor.sucessoRegistro"
    static let syncSucesso = "br.gov.sp.educacao.sedprofessor.sucesso"
    static let titulo = "br.gov.sp.educacao.sedprofessor.titulo"
    static let turmas = "br.gov.sp.educacao.sedprofessor.turmas"
    static let ultimoAcessso = "br.gov.sp.educacao.sedprofessor.ultimoAcessso"
}
